[package]
name = "zkdoc_server"
version = "0.0.1"
edition = "2021"
publish = false

[dependencies]
actix-web = "4"
serde.workspace = true
actix-cors = "0.6.4"
log = "0.4.0"
env_logger = "0.9.0"
zkdoc_sdk = { path = "../zkdoc_sdk" }
