[package]
name = "zkdoc_server"
version = "0.0.0"
edition = "2021"


[dependencies]
actix-web = "4"
serde = { version = "1.0", features = ["derive"] }
actix-cors = "0.6.4"
# logging
log = "0.4.0"
env_logger = "0.9.0"

# local lib
zkdoc_sdk.workspace = true
